[package]
name = "neighborhood-diversity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colors-transform = "0.2.11"
criterion = "0.4"
network_vis = "0.1.2"
rand = "0.8"

[[bench]]
name = "random_graphs"
harness = false
