[package]
name = "neighborhood-diversity"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ludwigschlame/neighborhood-diversity/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
network_vis = "0.1"
colors-transform = "0.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "random_graphs"
harness = false

[[bench]]
name = "co_graphs"
harness = false

[profile.release]
debug = true # necessary for flamegraph
