[package]
name = "neighborhood-diversity"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ludwigschlame/neighborhood-diversity/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = { version = "1.7", optional = true }
network_vis = { version = "0.1", optional = true }
colors-transform = { version = "0.2", optional = true }

[dev-dependencies]
criterion = "0.5"
pretty_assertions = "1.3"
rayon = "1.7"

[features]
default = ["par"]
par = ["dep:rayon"]
vis = ["dep:network_vis", "dep:colors-transform"]

[[bench]]
name = "random_graphs"
harness = false

[[bench]]
name = "co_graphs"
harness = false
